jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - python/install-packages:
          pip-dependency-file: tests/requirements.txt
          pkg-manager: pip
      - run:
          command: |
            python -b -m pytest --cov=privacyidea tests/
          name: Test
orbs:
  python: circleci/python@1.1.0

version: 2.1
workflows:
  main:
    jobs:
      - build
